backend/app/main.py
=> feat: catch-all route in FastAPI allows for deep links in prod (#25)

.gitignore, backend/app/main.py, frontend/src/api/__tests__/common.spec.ts, frontend/src/api/__tests__/misc.spec.ts, frontend/src/api/annonars.ts, frontend/src/api/common.ts, frontend/src/api/misc.ts, frontend/src/components/HeaderDefault.vue, frontend/src/components/__tests__/HeaderDefault.spec.ts, frontend/src/components/__tests__/HeaderDetailPage.spec.ts, frontend/src/stores/__tests__/geneInfo.spec.ts, frontend/src/stores/__tests__/misc.spec.ts, frontend/src/stores/geneInfo.ts, frontend/src/stores/misc.ts, frontend/src/views/GeneDetailView.vue, frontend/src/views/__tests__/AboutView.spec.ts, frontend/src/views/__tests__/ContactView.spec.ts, frontend/src/views/__tests__/GeneDetailView.spec.ts, frontend/src/views/__tests__/HomeView.spec.ts, utils/docker/Dockerfile, utils/docker/build-docker.sh
=> feat: put the current version into docker image and display (#28)

frontend/src/components/HeaderDetailPage.vue, frontend/src/components/__tests__/HeaderDetailPage.spec.ts, frontend/src/router/index.ts
=> fix: Search works only from second time (#23, #24)

frontend/src/api/__tests__/common.spec.ts, frontend/src/api/common.ts, frontend/src/api/mehari.ts, frontend/src/assets/__tests__/BRCA1TxInfo.json, frontend/src/stores/__tests__/variantInfo.spec.ts, frontend/src/stores/variantAcmgRating.ts, frontend/src/stores/variantInfo.ts
This provides access to all affected genes in a SV. Note that this also changes keys from kebab-case to snake_case.
=> feat: integration of meahri 0.8.0 (#56)

frontend/src/components/VariantDetails/VariationLandscape.vue, frontend/src/lib/utils.ts, frontend/src/stores/__tests__/variantInfo.spec.ts, frontend/src/stores/variantInfo.ts, frontend/src/views/VariantDetailView.vue, frontend/src/views/__tests__/VariantDetailView.spec.ts, frontend/vitest.config.ts
=> fix: Non existing variants are not handled gracefully (#109)

backend/app/api/internal/endpoints/remote.py, backend/env.dev, frontend/src/components/SvDetails/AcmgRating.vue, frontend/src/lib/acmgCNV.ts, frontend/src/router/index.ts, frontend/src/views/ACMGSVDocs.vue, frontend/src/views/__tests__/ACMGSVDocs.spec.ts
Added conflicting evidences and fixed some other small things
=> feat: Conflicting evidences in ACMG SV criteria

frontend/src/components/SvDetails/SvGenes.vue, frontend/src/views/VariantDetailView.vue
=> fix: Add linkout for genes in SV page (#152)

frontend/src/lib/__tests__/utils.spec.ts, frontend/src/lib/utils.ts
=> feat: Add support for commas in numbers in search Queries (#147)

.gitignore, backend/app/api/api_v1/api.py
=> feat: towards complete integration of OrcID setup (#96)

frontend/index.html, frontend/src/main.ts, frontend/src/plugins/matomo.ts
=> fix: Matomo records 

backend/app/core/config.py, backend/app/main.py, utils/docker/.gitignore
=> fix: Docs are rendered properly (#201)

backend/app/api/api_v1/api.py, backend/app/api/internal/api.py, backend/app/api/internal/endpoints/proxy.py, backend/app/api/internal/endpoints/remote.py, docs/api_api_v1.rst, docs/api_internal.rst, docs/api_models.rst
=> fix: Path in docs

frontend/src/views/AboutView.vue
=> feat: Update Info in About (#209)

backend/Pipfile, backend/Pipfile.lock, backend/app/api/internal/api.py, backend/app/main.py, frontend/package-lock.json, frontend/package.json, frontend/src/plugins/index.ts, frontend/src/plugins/matomo.ts, frontend/src/plugins/sentry.ts
=> feat: integrating sentry (#240)

frontend/src/components/FooterDefault.vue, frontend/src/components/StaticViews/TermsView.vue, frontend/src/views/HomeView.c.ts, frontend/src/views/HomeView.vue, frontend/src/views/LoginView.vue
=> feat: adjust landing and static pages to NAR WSI requirements (#303)

frontend/src/components/SeqvarDetails/VariantScoresCard.vue
=> feat: Display all MMSplice and SpliceAI Scores (#296)

backend/app/main.py, frontend/env.d.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/FooterDefault.vue, frontend/src/components/PageHeader.vue, frontend/src/components/__tests__/FooterDefault.spec.ts, frontend/src/plugins/sentry.ts, frontend/vite.config.ts, utils/docker/Dockerfile, utils/docker/build-docker.sh
=> feat: enable sentry user feedback and releases (#329)

frontend/src/components/CaseInformationCard.vue, frontend/src/components/SeqvarDetails/ClinsigCard.vue, frontend/src/lib/acmgSeqVar.ts
=> feat: deprecation warning for PP3_strong + PM1_strong (#324)

backend/app/api/deps.py, backend/app/main.py
=> fix: more robust handling of async sessions (#360)

backend/app/api/internal/endpoints/remote.py
=> fix: more robust handling of InterVar result

docs/doc_queries.rst
=> docs: Refactoring of allowed queries documentation

frontend/src/api/intervar.ts
=> fix: Loading the ACMG criteria from intervar

frontend/package-lock.json, frontend/package.json, frontend/src/lib/modulesDeclarations.d.ts
=> feat: bump rfl to integrate plotly-based clinvar landscape (#430)

docs/dev_frontend.rst, docs/doc_manual.rst
=> docs: documenting ACMG criteria (#429)

backend/app/api/api_v1/api.py
feat: Allow users to link their account with more login sources (#185) (#535)"
This reverts commit a0156ee8a30290cc1e5721d505df2b508275d2ab.
=> chore: Revert "feat: Allow users to link their account with more login sources"

docs/doc_manual.rst, frontend/src/components/ClinvarsubCard/ClinvarsubCard.vue, frontend/src/lib/query.ts, frontend/src/stores/strucvarAcmgRating/store.ts, frontend/src/views/GeneDetailView/GeneDetailView.spec.ts, frontend/src/views/StrucvarDetailsView/StrucvarDetailsView.vue
=> chore: bump rfl "add collapse button for pubtator results" (#585)

frontend/src/api/autoacmg/client.spec.ts, frontend/src/api/autoacmg/client.ts
Added long await to the client
=> fix: Add long await to the client (#822)
