.github/workflows/release-please.yml

ci: use secrets.BOT_TOKEN for release-please

---

backend/app/main.py

fix: adjust default backend service ports for prod

---

.github/workflows/docker-build.yml

fix: write git version to VERSION in CI

---

backend/app/main.py
frontend/package-lock.json
frontend/package.json
frontend/src/api/__tests__/utils.spec.ts
frontend/src/api/annonars.ts
frontend/src/api/utils.ts
frontend/src/components/HeaderDefault.vue
frontend/src/components/HeaderDetailPage.vue
frontend/src/components/VariantDetails/BeaconNetwork.vue
frontend/src/components/VariantDetails/FreqsAutosomal.vue
frontend/src/components/VariantDetails/FreqsMitochondrial.vue
frontend/src/components/VariantDetails/TxCsq.vue
frontend/src/components/VariantDetails/VariantConservation.vue
frontend/src/components/VariantDetails/VariantFreqs.vue
frontend/src/components/VariantDetails/VariantTools.vue
frontend/src/components/VariantDetails/VariantValidator.vue
frontend/src/components/__tests__/HeaderDefault.spec.ts
frontend/src/router/index.ts
frontend/src/stores/geneInfo.ts
frontend/src/stores/genesList.ts
frontend/src/stores/misc.ts
frontend/src/views/GenesListView.vue
frontend/src/views/HomeView.vue
frontend/src/views/__tests__/HomeView.spec.ts

feat: Implementation of search for general entries (#20)

---

frontend/src/api/__tests__/utils.spec.ts
frontend/src/api/utils.ts
frontend/src/views/AboutView.vue
frontend/src/views/__tests__/AboutView.spec.ts

feat: Acknowledgements in about view (#42)

---

frontend/src/api/__tests__/annonars.spec.ts
frontend/src/api/__tests__/utils.spec.ts
frontend/src/components/VariantDetails/VariantValidator.vue
frontend/src/components/__tests__/ClinVar.spec.ts
frontend/src/components/__tests__/FreqsAutosomal.spec.ts
frontend/src/components/__tests__/FreqsMitochondrial.spec.ts
frontend/src/components/__tests__/VariantFreqs.spec.ts
frontend/src/components/__tests__/VariantTools.spec.ts
frontend/src/components/__tests__/VariantValidator.spec.ts
frontend/src/stores/__tests__/genesList.spec.ts
frontend/src/stores/__tests__/misc.spec.ts
frontend/src/stores/__tests__/variantInfo.spec.ts
frontend/src/stores/geneInfo.ts
frontend/src/stores/genesList.ts
frontend/src/stores/variantInfo.ts
frontend/src/views/__tests__/GeneDetailView.spec.ts
frontend/src/views/__tests__/GenesListView.spec.ts
frontend/src/views/__tests__/VariantDetailView.spec.ts

chore: Various test updates (#38)

---

frontend/src/components/VariantDetails/AcmgRating.vue
frontend/src/components/VariantDetails/BeaconNetwork.vue
frontend/src/components/VariantDetails/FreqsAutosomal.vue
frontend/src/components/VariantDetails/FreqsMitochondrial.vue
frontend/src/components/VariantDetails/VariantFreqs.vue
frontend/src/components/VariantDetails/VariantTools.vue
frontend/src/components/VariantDetails/VariantValidator.vue
frontend/src/router/index.ts
frontend/src/stores/genesList.ts
frontend/src/stores/variantAcmgRating.ts
frontend/src/stores/variantInfo.ts
frontend/src/views/PathNotFound.vue
frontend/src/views/VariantDetailView.vue
frontend/src/views/__tests__/PathNotFound.spec.ts

fix: Add type definitions (#68)

---

frontend/src/lib/acmgCNV.ts

feat: Add tool for ACMG assessment of CNVs (#59)

---

docs/dev_quickstart.rst

docs: adding alembic-upgrade notes to quickstart

---

frontend/vite.config.ts

fix: properly setup vite proxy for development

---

frontend/src/api/auth.ts

fix: login URL generation

---

backend/app/api/internal/endpoints/proxy.py
backend/app/core/config.py
backend/tests/api/internal/test_proxy.py
frontend/src/api/__tests__/auth.spec.ts
frontend/src/api/__tests__/dotty.spec.ts
frontend/src/api/common.ts
frontend/src/api/dotty.ts
frontend/src/components/HeaderDetailPage.vue
frontend/src/components/VariantDetails/VariationLandscape.vue
frontend/src/components/__tests__/HeaderDetailPage.spec.ts
frontend/src/components/__tests__/SearchBar.spec.ts
frontend/src/lib/__tests__/utils.spec.ts
frontend/src/lib/utils.ts
frontend/src/views/HomeView.vue
frontend/src/views/__tests__/HomeView.spec.ts

feat: integrate dotty to allow querying for HGVS variants (#101)

---

frontend/src/assets/__tests__/BRCA1Transcripts.json
frontend/src/components/ClinVarFreqPlot.vue
frontend/src/components/GtexGenePlot.vue
frontend/src/components/SvDetails/SvGenes.vue
frontend/src/components/VariationLandscape.vue
frontend/src/components/VegaPlot.vue
frontend/src/components/__tests__/VariationLandscape.spec.ts

fix: Add support for large displays (#113)

---

frontend/src/components/VariantDetails/TxCsq.vue

Consequences are present correctly now.

fix: Consequences display (#116)

---

frontend/src/lib/__tests__/utils.spec.ts
frontend/src/lib/utils.ts

Display 0 instead of NaN in frequencies card.

fix: Display 0 instead of Nan (#119)

---

frontend/src/components/VariantDetails/VariantValidator.vue

fix: Update link to variant validator (#122)

---

frontend/src/components/VariantDetails/VariantTools.vue

fix: Linkout to UCSC (#121)

---

frontend/src/components/VariantDetails/VariantTools.vue

fix: Correctly present CADD missing scores (#125)

---

frontend/src/components/VariantDetails/ClinVar.vue
frontend/src/components/__tests__/VariantDetails/ClinVar.spec.ts

Update frontend to show clinvar information.

fix: Present Clinvar information (#124)

---

frontend/src/api/__tests__/dotty.spec.ts
frontend/src/api/dotty.ts
frontend/src/components/VariationLandscape.vue
frontend/src/lib/utils.ts

fix: Update scores for lollipops clinvar plot (#137)

---

backend/Pipfile
backend/Pipfile.lock
frontend/src/components/VariantDetails/ScoreDisplay.vue
frontend/src/components/VariantDetails/VariantTools.vue

Fixed score display bug correlated to null values.

fix: Revel score for nonsense variant (#126)

---

frontend/src/lib/utils.ts

Search call to dotty just missed assembly argument

fix: Input assembly arg for dotty (#141)

---

frontend/src/components/SearchBar.vue

fix: Add keydown entry to text-field in search bar (#144)

---

frontend/src/views/SvDetailView.vue

fix: Remove 1000 suffix in genome browser coordinates (#146)

---

frontend/src/components/SvDetails/SvTools.vue
frontend/src/components/__tests__/SvDetails/SvTools.spec.ts
frontend/src/views/SvDetailView.vue
frontend/src/views/__tests__/SvDetailView.spec.ts

feat: Link-outs in SV detail page (#143)

---

frontend/src/components/HeaderDefault.vue
frontend/src/router/index.ts
frontend/src/views/PrivacyView.vue
frontend/src/views/TermsView.vue

feat: create pages for red tape (#156)

---

frontend/src/components/HeaderDefault.vue
frontend/src/components/HeaderDetailPage.vue
frontend/src/components/__tests__/HeaderDefault.spec.ts
frontend/src/components/__tests__/HeaderDetailPage.spec.ts
frontend/src/views/__tests__/ACMGCriteriaDoc.spec.ts
frontend/src/views/__tests__/ACMGSVDocs.spec.ts
frontend/src/views/__tests__/AboutView.spec.ts
frontend/src/views/__tests__/ContactView.spec.ts
frontend/src/views/__tests__/GeneDetailView.spec.ts
frontend/src/views/__tests__/GenesListView.spec.ts
frontend/src/views/__tests__/HomeView.spec.ts
frontend/src/views/__tests__/VariantDetailView.spec.ts

fix: menu links for details page and tests

---

frontend/src/components/FooterDefault.vue
frontend/src/components/HeaderDefault.vue
frontend/src/components/__tests__/FooterDefault.spec.ts
frontend/src/components/__tests__/HeaderDefault.spec.ts
frontend/src/views/AboutView.vue
frontend/src/views/__tests__/AboutView.spec.ts

feat: Change title

---

frontend/src/lib/test-utils.ts
frontend/src/views/GenesListView.vue
frontend/src/views/__tests__/GenesListView.spec.ts

fix: Change redirection method in genes entrypoint (#161)

---

frontend/src/components/CaseInformationCard.vue
frontend/src/components/HeaderDefault.vue
frontend/src/components/__tests__/CaseInformationCard.spec.ts
frontend/src/components/__tests__/HeaderDefault.spec.ts
frontend/src/stores/__tests__/case.spec.ts
frontend/src/stores/case.ts
frontend/src/views/HomeView.vue

feat: Case specific data functionality (#93)

---

backend/app/api/internal/api.py
backend/app/core/config.py
backend/tests/test_main.py
frontend/package-lock.json
frontend/package.json
frontend/src/api/__tests__/settings.spec.ts
frontend/src/api/settings.ts
frontend/src/main.ts
frontend/src/plugins/index.ts
frontend/src/plugins/matomo.ts
frontend/vite.config.ts

feat: Integration of Matomo (#43)

---

frontend/index.html
frontend/src/plugins/matomo.ts

fix: Proper matomo url (#183)

---

frontend/src/main.ts

fix: Docker build

---

docs/acmg_cnvs_criteria.rst
docs/acmg_cnvs_details.rst
docs/index.rst

docs: explaining implementation of ACMG 2020 CNV assessment (#195)

---

frontend/src/stores/misc.ts

fix: Rebuild docker container

---

docs/api_api_v1.rst
docs/api_internal.rst
docs/api_models.rst

fix: Documentation of APIs (#201)

---

backend/app/backend_pre_start.py

fix: Close db connection on startup (#205)

---

frontend/src/components/GeneDetails/ClinvarCard/ClinvarImpact.vue

fix: using text-no-wrap on ClinvarImpact table

---

frontend/src/components/GeneDetails/ClinvarCard/ClinvarImpact.vue

fix: make clinvar impact table more robust, ignore labels

---

frontend/src/plugins/sentry.ts

chore: fix sentry key

---

.github/workflows/main.yml
frontend/Makefile
frontend/src/views/__tests__/GeneDetailView.spec.ts

ci: single-threaded frontend tests

---

frontend/src/components/GeneDetails/ConditionsCard.vue
frontend/src/lib/__tests__/utils.spec.ts
frontend/src/lib/utils.ts

fix: OMIM id extraction for link-out (#260)

---

frontend/src/components/SeqvarDetails/VariantScoresCard.vue

fix: message when SpliceAI prediction unavailable

---

frontend/src/components/SeqvarDetails/ClinsigCard.vue
frontend/src/stores/variantAcmgRating.ts
frontend/src/views/SeqvarDetailsView.vue
frontend/src/views/__tests__/GeneDetailView.spec.ts
frontend/src/views/__tests__/SeqvarDetailsView.spec.ts

fix: fix blipping seqvar ACMG card (#266)

---

frontend/src/views/GeneDetailView.vue
frontend/src/views/HomeView.vue
frontend/src/views/SeqvarDetailsView.vue
frontend/src/views/__tests__/GeneDetailView.spec.ts
frontend/src/views/__tests__/SeqvarDetailsView.spec.ts

feat: more consistent UI design on seqvar details page (#217)

---

frontend/src/components/FooterDefault.vue
frontend/src/views/StrucvarDetailsView.vue
frontend/src/views/__tests__/StrucvarDetailsView.spec.ts

feat: more consistent UI design on strucvar details page (#218)

---

frontend/src/components/PageHeader.vue
frontend/src/plugins/vuetify.ts
frontend/src/views/GeneDetailView.vue
frontend/src/views/HomeView.vue
frontend/src/views/SeqvarDetailsView.vue
frontend/src/views/StrucvarDetailsView.vue

fix: make gray backround also work with dark theme (#276)

---

frontend/src/stores/__tests__/variantInfo.spec.ts
frontend/src/stores/seqVarInfo.ts
frontend/src/views/SeqvarDetailsView.vue

fix: Present hpo terms on seqvar page (#286)

---

frontend/src/views/SeqvarDetailsView.vue
frontend/src/views/StrucvarDetailsView.vue

feat: additional `Jump to IGV` button (#297)

---

frontend/src/components/SeqvarDetails/ClinsigCard.vue
frontend/src/components/__tests__/SeqvarDetails/ClinsigCard.spec.ts

feat: change default presentation of ACMG criteria (#287)

---

frontend/src/views/SeqvarDetailsView.vue

feat: Move scores card above population frequencies card (#294)

---

docs/doc_manual.rst
docs/index.rst
frontend/src/components/DocsLink.vue
frontend/src/components/GeneDetails/ClinvarCard.vue
frontend/src/components/GeneDetails/ConditionsCard.vue
frontend/src/components/GeneDetails/ExpressionCard.vue
frontend/src/components/GeneDetails/OverviewCard.vue
frontend/src/components/GeneDetails/PathogenicityCard.vue
frontend/src/components/GenomeBrowser.vue
frontend/src/components/SeqvarDetails/BeaconNetworkCard.vue
frontend/src/components/SeqvarDetails/ClinsigCard.vue
frontend/src/components/SeqvarDetails/ClinvarCard.vue
frontend/src/components/SeqvarDetails/FreqsCard.vue
frontend/src/components/SeqvarDetails/TxCsqCard.vue
frontend/src/components/SeqvarDetails/VariantScoresCard.vue
frontend/src/components/SeqvarDetails/VariantToolsCard.vue
frontend/src/components/SeqvarDetails/VariantValidatorCard.vue
frontend/src/components/StrucvarDetails/ClinsigCard.vue
frontend/src/components/StrucvarDetails/ClinvarCard.vue
frontend/src/components/StrucvarDetails/GeneListCard.vue
frontend/src/components/StrucvarDetails/VariantToolsCard.vue

feat: link out from app to documentation (#308)

---

frontend/src/views/HomeView.vue

chore: add note about session cookies on home page

---

frontend/src/components/SeqvarDetails/ClinsigCard.vue
frontend/src/views/HomeView.c.ts
frontend/src/views/__tests__/HomeView.spec.ts

feat: add conflict display between PVS1 and PM4/PP3 (#290)

---

docs/acmg_seqvars_criteria.rst
docs/doc_manual.rst
docs/index.rst
docs/refs.bib

docs: filling the application's manual (#309)

---

frontend/src/components/SeqvarDetails/ClinsigCard/CriterionSwitch.vue
frontend/src/lib/acmgSeqVar.ts

feat: restrict upgrade/downgrade of AMCG seqvar criteria (#291)

---

frontend/src/api/dotty.ts

fix: properly urlencode arguments to dotty API call (#323)

---

frontend/src/lib/query.ts

fix: make querying for HGNC ID go to the gene (#327)

---

frontend/src/components/VarDetails/ClinvarsubCard.vue
frontend/src/stores/clinvarsub.ts

fix: properly handle anonymous sessions in clinvarsub card (#328)

---

frontend/src/components/SeqvarDetails/ClinsigCard.vue
frontend/src/components/SeqvarDetails/ClinsigCard/SummarySheet.vue
frontend/src/components/StrucvarDetails/ClinsigCard.vue
frontend/src/components/VarDetails/ClinvarsubCard.vue
frontend/src/stores/seqVarAcmgRating.ts

fix: properly handler errors / empty results from InterVar (#322)

---

frontend/src/components/GeneDetails/ClinvarCard/ClinvarFreqPlot.vue
frontend/src/components/GeneDetails/ClinvarCard/VariationLandscape.vue
frontend/src/components/GeneDetails/ExpressionCard.vue
frontend/src/components/VegaPlot.vue

fix: vega plot background colors in dark mode (#284)

---

frontend/src/plugins/sentry.ts

feat: enable Sentry user feedback

---

frontend/src/plugins/sentry.ts

revert: disable sentry feedback again

---

backend/app/api/internal/endpoints/remote.py
docs/doc_manual.rst
frontend/src/components/GeneDetails/LiteratureCard.vue
frontend/src/components/GeneDetails/OverviewCard.vue
frontend/src/components/VarDetails/ClinvarsubCard.vue
frontend/src/stores/pubtator.ts
frontend/src/views/GeneDetailView.vue
frontend/src/views/SeqvarDetailsView.vue
frontend/src/views/StrucvarDetailsView.vue
frontend/src/views/__tests__/GeneDetailView.spec.ts

feat: integrate with PubTator 3 API (#312)

---

frontend/src/api/viguno.ts
frontend/src/components/CaseInformationCard.vue
frontend/src/stores/__tests__/terms.spec.ts
frontend/src/stores/case.ts
frontend/src/stores/terms.ts

feat: improve HPO lookup result quality with latest viguno (#338)

---

frontend/src/components/SeqvarDetails/TxCsqCard.vue

fix: properly display MANE transcripts (#293)

---

frontend/src/lib/__tests__/genomicVars.spec.ts
frontend/src/lib/genomicVars.ts
frontend/src/views/HomeView.c.ts
frontend/src/views/QueryView.vue

fix: resolve issues with example links on home view (#350)

---

frontend/src/lib/utils.ts
frontend/src/views/HomeView.vue
frontend/src/views/__tests__/HomeView.spec.ts

feat: using links for home view examples (#349)

---

frontend/src/plugins/sentry.ts

feat: enable user feedback after fixing it on the server

---

backend/app/schemas/__init__.py
backend/app/schemas/acmgseqvar.py
backend/app/schemas/bookmark.py
backend/app/schemas/clinvarsub.py
backend/app/schemas/common.py
backend/tests/api/api_v1/test_acmgseqvar.py
backend/tests/api/api_v1/test_bookmarks.py
backend/tests/app/test_schemas.py
backend/tests/conftest.py
backend/tests/crud/test_acmgseqvar.py
backend/tests/crud/test_bookmark.py
frontend/src/api/__tests__/acmgseqvar.spec.ts
frontend/src/lib/__tests__/genomicVars.spec.ts
frontend/src/lib/genomicVars.ts
frontend/src/stores/seqVarAcmgRating.ts

feat: improved validation for writing bookmarks etc. (#365)

---

.readthedocs.yaml
docs/requirements.txt

docs: Fixing dependencies conflicts

---

frontend/src/components/GeneDetails/ConditionsCard.vue

feat: integrate PanelApp in gene details card

---

frontend/src/components/GeneDetails/PathogenicityCard.vue
frontend/src/components/SeqvarDetails/FreqsCard/AutosomalFreqs.vue

feat: integrate new gnomAD v4 data

---

frontend/src/components/SeqvarDetails/VariantScoresCard.vue

feat: integrate AlphaMissense display in scores

---

frontend/src/api/__tests__/acmgSeqvar.spec.ts
frontend/src/api/__tests__/annonars.spec.ts
frontend/src/api/__tests__/mehari.spec.ts
frontend/src/api/acmgSeqvar.ts
frontend/src/api/annonars.ts
frontend/src/api/mehari.ts
frontend/src/stores/seqvarAcmgRating.ts
frontend/src/stores/seqvarInfo.ts
frontend/src/stores/strucvarInfo.ts

feat: Use Seqvar and LinearStrucvar whenever possible (#366)

---

frontend/src/components/SeqvarDetails/FreqsCard/AutosomalFreqs.vue
frontend/src/components/SeqvarDetails/VariantScoresCard.vue

fix: Expantion of MMSplice and SpliceAI scores properly handle Infinity scores (#381)

---

backend/app/api/internal/endpoints/remote.py
frontend/src/api/__tests__/acmgSeqvar.spec.ts
frontend/src/api/acmgSeqvar.ts
frontend/src/api/intervar.ts
frontend/src/components/SeqvarDetails/ClinsigCard.vue
frontend/src/stores/__tests__/seqvarAcmgRating.spec.ts
frontend/src/stores/seqvarAcmgRating.ts

fix: ACMG criteria can not be saved to the server (#379)

---

frontend/src/components/GeneDetails/LiteratureCard.vue

fix: Adjust colors of highlightings in dark mode (#393)

---

frontend/src/components/GeneDetails/ConditionsCard.vue

feat: Add sorting to PanelApp (#397)

---

frontend/src/components/GeneDetails/ConditionsCard.vue

feat: Provide linkouts for PanelApps (#408)

---

frontend/src/components/GeneDetails/ConditionsCard.vue
frontend/src/components/GeneDetails/LiteratureCard.vue

feat: Literature higlight in dark mode (#407)

---

frontend/src/components/GeneDetails/ConditionsCard.vue

fix: Replace acmgSf data with hgnc one in PanelApp (#416)

---

docs/doc_quickstart.rst

docs: adding introduction section to section Quickstart

---

docs/doc_tutorial.rst

docs: describing advantages of login at the end of tutorial

---

backend/app/api/api_v1/endpoints/bookmarks.py
backend/tests/api/api_v1/test_bookmarks.py
frontend/src/api/bookmarks.ts
frontend/src/components/BookmarkListItem.vue
frontend/src/stores/bookmarks.ts

feat: Change API status code for not found bookmarks (#387)

---

backend/app/api/api_v1/endpoints/acmgseqvar.py
backend/tests/api/api_v1/test_acmgseqvar.py
frontend/src/api/acmgSeqvar.ts
frontend/src/stores/seqvarAcmgRating.ts

feat: Change API status code for nor found ACMG ratings (#388)

---

frontend/src/components/GeneDetails/LiteratureCard.vue

feat: Improvements in Literature highlighting (#427)

---

frontend/src/lib/modulesDeclarations.d.ts

feat: Cleanup module Declarations (#458)

---

backend/Makefile
backend/app/initial_data.py

fix: Fix initial superuser setup (#460)

---

backend/alembic/versions/6f14afa8ea47_update_auth_models.py
backend/app/api/api_v1/api.py

fix: Proper naming of openid accounts (#533)

---

backend/app/api/api_v1/api.py

feat: Allow users to link their account with more login sources (#185)

---

backend/app/api/api_v1/api.py

fix: Proper redirect link for authentification callback

---

backend/alembic/versions/27c3977494f7_init_bookmarks.py
backend/alembic/versions/397feb4e1315_update_json_keys_caseinfo.py
backend/alembic/versions/4f3b20f156c1_init_caseinfo.py
backend/alembic/versions/6f14afa8ea47_update_auth_models.py
backend/alembic/versions/850ccab0221d_init_clinvarsub.py
backend/alembic/versions/8ccd31a4f116_init_adminmsgs.py
backend/alembic/versions/c8009ed33089_init_users.py
backend/alembic/versions/d10fec1c88fc_init_acmgseqvar.py
backend/app/api/internal/endpoints/remote.py
backend/tests/app/test_clinvarsub.py

fix: Disable cert verification in httpx Asyncclient for AutoCNV issue

---

frontend/package.json
frontend/src/plugins/vuetify.ts
frontend/src/views/SeqvarDetailsView/SeqvarDetailsView.vue

fix: bump rfl to support new annonars ClinVar XML format (#719)

---

backend/Pipfile
backend/Pipfile.lock

fix: Add proper dependency for yaml

---

frontend/src/api/autoacmg/client.ts

fix: Revert fetch with retry

---

.github/workflows/docker-build.yml

ci: add sha labels for Docker tags
